name: ipsupport_cm
description: CM Project
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  google_maps_flutter: ^2.3.1
  permission_handler: ^10.4.1
  firebase_storage: ^11.2.4
  file_picker: ^5.3.2
  shake: ^2.2.0

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/app/Splash_IPSupport.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/app/Icon_IPSupport.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app/Icon_IPSupport_android.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/app/
    - assets/images/
