// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL7wFMf8dhq6mXTy3s4betrhVWy7-1qhE',
    appId: '1:238573894807:web:a42e7d7a692883a3f5bdd2',
    messagingSenderId: '238573894807',
    projectId: 'ipsupport-28bbe',
    authDomain: 'ipsupport-28bbe.firebaseapp.com',
    storageBucket: 'ipsupport-28bbe.appspot.com',
    measurementId: 'G-0VMZCM64G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsbuAQTXfaLBJTcUDbtMEOoIc5QZFt6sM',
    appId: '1:238573894807:android:4450245f67a7848cf5bdd2',
    messagingSenderId: '238573894807',
    projectId: 'ipsupport-28bbe',
    storageBucket: 'ipsupport-28bbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeA4S6ksGPkudA2NM92_S-LygflUzNKRg',
    appId: '1:238573894807:ios:8da51999bfdb1090f5bdd2',
    messagingSenderId: '238573894807',
    projectId: 'ipsupport-28bbe',
    storageBucket: 'ipsupport-28bbe.appspot.com',
    iosClientId: '238573894807-lam93sseudgc0idnef87n7jlbu7lluji.apps.googleusercontent.com',
    iosBundleId: 'com.example.ipsupportCm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeA4S6ksGPkudA2NM92_S-LygflUzNKRg',
    appId: '1:238573894807:ios:8da51999bfdb1090f5bdd2',
    messagingSenderId: '238573894807',
    projectId: 'ipsupport-28bbe',
    storageBucket: 'ipsupport-28bbe.appspot.com',
    iosClientId: '238573894807-lam93sseudgc0idnef87n7jlbu7lluji.apps.googleusercontent.com',
    iosBundleId: 'com.example.ipsupportCm',
  );
}
